/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/goliat.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 0]}
        rotation={[2.4, -0.5, -1.95]}
        scale={[5.4, 3.7, 0.5]}
        userData={{ name: "Cube" }}
      />
    </group>
  );
}

useGLTF.preload("/goliat.glb");
